version: '3'

networks:
  mynet:
    driver: bridge

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: untertaxi_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - mynet
  web:
    build: ..
    volumes:
      - ..:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    networks:
      - mynet
